const assert = require('node:assert/strict');
const {classifyGesture,bindInput,mount} = require('../lg_assistant/web/static/smart-ring.js');
assert.equal(classifyGesture({dx:40,dy:3}),'next');
assert.equal(classifyGesture({dx:-40,dy:3}),'previous');
assert.equal(classifyGesture({dy:50}),null);
assert.equal(classifyGesture({duration:800}),'back');
assert.equal(classifyGesture({duration:800,cancelled:true}),null);
assert.equal(classifyGesture({dx:100,inspect:true}),null);
const events={},actions=[],rotations=[];let inspecting=false;
const button={disabled:false,classList:{add(){},remove(){}},setPointerCapture(){},addEventListener(k,fn){events[k]=fn;}};
bindInput(button,{action:a=>actions.push(a),inspect:()=>inspecting,rotate:(x,y)=>rotations.push([x,y])});
const event=(o={})=>({pointerId:1,isPrimary:true,button:0,clientX:0,clientY:0,timeStamp:0,detail:1,preventDefault(){},stopPropagation(){},...o});
const emit=(name,o)=>events[name](event(o));
function gesture(up,moves=[]){emit('pointerdown');moves.forEach(m=>emit('pointermove',m));emit('pointerup',up);emit('click');}
gesture({timeStamp:100});assert.deepEqual(actions,['press']);
gesture({clientX:60,timeStamp:200});assert.deepEqual(actions,['press','next'],'swipe must not also submit a photo');
gesture({timeStamp:800});assert.deepEqual(actions,['press','next','back'],'long press must not also submit');
gesture({clientY:70,timeStamp:200});assert.equal(actions.length,3,'vertical scroll is not tap');
gesture({timeStamp:800},[{clientX:50},{clientX:0}]);assert.equal(actions.length,3,'drag out and back must not become long press');
emit('pointerdown');emit('pointercancel');emit('click');assert.equal(actions.length,3);
emit('click',{detail:0});assert.equal(actions.at(-1),'press','keyboard activation remains available');
inspecting=true;gesture({clientX:50,timeStamp:400},[{clientX:50,clientY:10}]);assert.equal(actions.length,4);assert.deepEqual(rotations[0],[50,10]);
emit('keydown',{key:'ArrowRight'});assert.deepEqual(rotations.at(-1),[15,0]);
inspecting=false;button.disabled=true;emit('click');assert.equal(actions.length,4,'busy native control cannot submit');
console.log('Smart ring: tap, swipe, hold, scroll/cancel, duplicate-click suppression, inspection and keyboard passed.');
// GPU loss must notify the host and stop drawing so native controls can take over.
let unavailable=0, scheduled=0, resizeStopped=false;
global.matchMedia=()=>({matches:false});
global.requestAnimationFrame=()=>++scheduled;
global.cancelAnimationFrame=()=>{};
global.ResizeObserver=class {observe(){} disconnect(){resizeStopped=true;}};
const gpuEvents={},modelClasses=new Set();
const gl=new Proxy({}, {get:(_,key)=>key==='getShaderParameter'||key==='getProgramParameter'?()=>true:()=>({})});
const model=mount({getContext:()=>gl,addEventListener:(type,fn)=>gpuEvents[type]=fn,parentElement:{classList:{add:n=>modelClasses.add(n),remove:n=>modelClasses.delete(n)}}},{onUnavailable:()=>unavailable++});
assert.ok(modelClasses.has('has-model'));
gpuEvents.webglcontextlost({preventDefault(){}});
assert.equal(unavailable,1);assert.equal(resizeStopped,true);assert.equal(modelClasses.has('has-model'),false);
const scheduledBefore=scheduled;model.rotate(10,10);model.setVisible(true);gpuEvents.webglcontextrestored();
assert.equal(scheduled,scheduledBefore,'lost renderer cannot restart');assert.equal(modelClasses.has('has-model'),false);
console.log('Smart ring: GPU loss notifies host, stops rendering, and preserves native fallback.');
