const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('../../frontend/node_modules/jsdom');
const {coordinates,amapUrl}=require('../lg_assistant/web/static/lens-map.js');
const source=fs.readFileSync(path.join(__dirname,'../lg_assistant/web/static/lens-map.js'),'utf8');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function setup({configured=true,fetchConfig=null,realIMU=false,sdkPending=false,fakeTimers=false}={}){
  const dom=new JSDOM('<section id="map"></section>',{url:'https://assistant.example/',runScripts:'outside-only',pretendToBeVisual:true}),win=dom.window;
  const requests=[],maps=[],finders=[],conversions=[],timers=new Map();let geo=0,success,error,stops=0,imu,imuChange,now=0,timerSequence=0;
  if(fakeTimers){win.setTimeout=(fn,delay)=>{const id=++timerSequence;timers.set(id,{fn,at:now+delay});return id;};win.clearTimeout=id=>timers.delete(id);}
  win.fetch=async(url,options)=>{requests.push({url,options});if(fetchConfig)return fetchConfig(url,options);return configured?{ok:true,status:200,json:async()=>({key:'test-js-key',serviceHost:'/_AMapService'})}:{ok:false,status:503,json:async()=>({error:'高德地图尚未配置，IMU 模拟仍可使用。'})};};
  const amap={Map:class{constructor(target,options){this.rotations=[];this.options=options;this.destroyed=false;maps.push(this);}setRotation(value){this.rotations.push(value);}setZoomAndCenter(zoom,center){this.center=center;}destroy(){this.destroyed=true;}zoomIn(){}zoomOut(){}},Marker:class{setMap(){}setAngle(){}},PlaceSearch:class{search(query,callback){finders.push({query,callback});}},convertFrom:(point,system,callback)=>conversions.push({point,system,callback})};
  if(!sdkPending)win.AMap=amap;
  if(realIMU){
    win.DeviceOrientationEvent=function(){};
    win.eval(fs.readFileSync(path.join(__dirname,'../lg_assistant/web/static/lens-imu.js'),'utf8'));
    const create=win.LensIMU.create;
    win.LensIMU.create=options=>{imu=create(options);const stop=imu.stop;imu.stop=()=>{stops++;return stop();};return imu;};
  }else win.LensIMU={create:({onChange})=>{imuChange=onChange;return {setHeading:value=>onChange({heading:((value%360)+360)%360,label:value===90?'东':'北',source:'manual'}),start:async()=>onChange({heading:90,label:'东',source:'sensor'}),calibrate:()=>onChange({heading:0,label:'北',source:'relative'}),stop:()=>stops++};}};
  Object.defineProperty(win.navigator,'geolocation',{value:{getCurrentPosition:(s,e)=>{geo++;success=s;error=e;}}});
  win.eval(source);const panel=win.document.getElementById('map'),feature=win.LensFeatures.map;feature.mount(panel);
  const el=name=>panel.querySelector(`[data-map="${name}"]`);
  const search=query=>{el('query').value=query;el('form').dispatchEvent(new win.Event('submit',{cancelable:true}));};
  const advance=ms=>{now+=ms;for(const [id,timer] of [...timers])if(timer.at<=now){timers.delete(id);timer.fn();}};
  return {win,feature,panel,el,search,requests,maps,finders,conversions,timers,advance,sdkReady:()=>{win.AMap=amap;},geo:()=>geo,success:value=>success(value),failure:value=>error(value),stops:()=>stops,imu:()=>imu,imuChange:value=>imuChange(value),close:()=>{feature.close();win.close();}};
}
(async()=>{
  assert.deepEqual(coordinates('31.23，121.47'),{latitude:31.23,longitude:121.47,name:'坐标位置',coordinate:'wgs84'});
  for(const invalid of ['Shanghai','91,0','0,181','NaN,0'])assert.equal(coordinates(invalid),null);
  const url=new URL(amapUrl({latitude:31,longitude:121,name:'我的位置',coordinate:'wgs84'}));assert.equal(url.hostname,'uri.amap.com');assert.equal(url.searchParams.get('coordinate'),'wgs84');
  let h=setup();h.feature.open();await flush();assert.equal(h.geo(),0,'opening the map does not request location');assert.equal(h.maps.length,1);
  assert.equal(h.win._AMapSecurityConfig.serviceHost,'https://assistant.example/_AMapService');assert.equal('securityJsCode' in h.win._AMapSecurityConfig,false,'security code remains on server');
  h.el('angle').value='90';h.el('angle').dispatchEvent(new h.win.Event('input'));assert.match(h.el('heading').textContent,/东.*90°/);assert.equal(h.maps[0].rotations.at(-1),-90,'east-facing heading rotates the map so east is up');
  h.el('follow').checked=false;h.el('follow').dispatchEvent(new h.win.Event('change'));assert.equal(h.maps[0].rotations.at(-1),0,'north-up remains available');
  h.search('上海');h.finders[0].callback('complete',{poiList:{pois:[{name:'上海站',address:'静安区',location:{lng:121.45,lat:31.25}}]}});h.el('locate').click();h.el('results').firstChild.click();await flush();
  h.success({coords:{latitude:40,longitude:120}});assert.equal(h.el('coordinates').textContent,'31.25000, 121.45000','late GPS callbacks cannot replace manually chosen AMap results');
  assert.equal(new URL(h.el('navigate').href).hostname,'uri.amap.com');assert.equal(new URL(h.el('navigate').href).searchParams.get('mode'),'walk');
  h.search('北京');h.feature.close();h.finders[1].callback('complete',{poiList:{pois:[{name:'北京',location:{lat:39.9,lng:116.4}}]}});assert.equal(h.el('results').children.length,0);assert.equal(h.maps[0].destroyed,true);assert.ok(h.stops()>0);h.close();
  h=setup();h.feature.open();await flush();h.search('31.23,121.47');assert.equal(h.conversions[0].system,'gps','browser/manual WGS84 positions are converted to AMap GCJ02');h.feature.close();h.conversions[0].callback('complete',{locations:[{lat:31.24,lng:121.48}]});await flush();assert.equal(h.maps[0].center,undefined,'late coordinate conversion cannot revive a closed map');h.close();
  h=setup({configured:false});h.feature.open();await flush();assert.match(h.el('status').textContent,/尚未配置/);assert.equal(h.maps.length,0);assert.equal(h.el('placeholder').hidden,false);h.el('angle').value='90';h.el('angle').dispatchEvent(new h.win.Event('input'));assert.match(h.el('heading').textContent,/90°/,'IMU simulation works without AMap credentials');h.search('上海');assert.equal(new URL(h.el('full').href).hostname,'uri.amap.com');assert.match(h.el('status').textContent,/打开高德搜索/);h.close();
  h=setup({configured:false});h.feature.open();await flush();
  h.imuChange({heading:359.6,label:'北',source:'relative',calibrated:true});
  assert.equal(h.el('dial').getAttribute('aria-valuenow'),'0','rounded values remain inside the slider bounds');
  assert.match(h.el('source').textContent,/已校准/);assert.doesNotMatch(h.el('source').textContent,/未校准/);
  let bubbled=0;h.win.document.addEventListener('keydown',()=>bubbled++);
  for(const [key,expected] of [['Home',0],['ArrowLeft',355],['ArrowRight',0],['ArrowUp',5],['ArrowDown',0],['End',359]]){
    const event=new h.win.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true});h.el('dial').dispatchEvent(event);
    assert.equal(h.el('angle').value,String(expected));assert.equal(event.defaultPrevented,true);
  }
  assert.equal(bubbled,0,'dial keys do not trigger hardware scene navigation');h.close();
  h=setup();h.feature.open();await flush();h.search('31.23,121.47');h.search('北京');assert.match(h.el('status').textContent,/正在搜索/);await flush();
  assert.match(h.el('status').textContent,/正在搜索/,'cancelled coordinate conversion cannot overwrite a newer search status');h.close();
  h=setup();h.feature.open();await flush();h.search('31.23,121.47');h.feature.close();await flush();h.feature.open();await flush();
  assert.equal(h.conversions.length,2);h.feature.close();const closedStatus=h.el('status').textContent;await flush();
  assert.equal(h.el('status').textContent,closedStatus,'map initialization waiting for a point does not report ready after close');h.close();
  let configReady;
  h=setup({fetchConfig:()=>new Promise(resolve=>{configReady=resolve;})});h.feature.open();
  assert.equal(h.el('locate').disabled,true,'location cannot cancel an in-flight map configuration request');h.el('locate').click();assert.equal(h.geo(),0);
  configReady({ok:true,status:200,json:async()=>({key:'test-js-key',serviceHost:'/_AMapService'})});await flush();
  assert.equal(h.maps.length,1);assert.equal(h.el('locate').disabled,false);h.close();
  h=setup({configured:false,realIMU:true});h.feature.open();await flush();h.el('angle').value='135';h.el('angle').dispatchEvent(new h.win.Event('input'));
  assert.equal(h.imu().status.heading,135);assert.equal(h.imu().status.source,'manual');
  h.el('sensor').click();const reading=new h.win.Event('deviceorientation');Object.assign(reading,{absolute:false,alpha:270,beta:90,gamma:0});h.win.dispatchEvent(reading);await flush();
  assert.equal(h.imu().status.source,'relative');h.el('calibrate').click();assert.equal(h.imu().status.heading,0);assert.match(h.el('source').textContent,/已校准/);
  h.feature.close();const afterClose=h.el('heading').textContent;Object.assign(reading,{alpha:180});h.win.dispatchEvent(reading);
  assert.equal(h.imu().status.source,'manual');assert.equal(h.el('heading').textContent,afterClose,'closed map ignores further physical orientation events');
  assert.equal(h.el('placeholder').hidden,false);h.close();
  h=setup({sdkPending:true,fakeTimers:true});h.feature.open();await flush();
  let script=h.win.document.querySelector('script[src^="https://webapi.amap.com/maps"]'),callback=new URL(script.src).searchParams.get('callback');
  assert.ok(callback,'SDK URL declares the official readiness callback');assert.equal(typeof h.win[callback],'function');
  const ready=h.win[callback];script.onload();await flush();
  assert.equal(h.maps.length,0);assert.match(h.el('status').textContent,/正在加载/,'entry script load is not mistaken for complete SDK readiness');
  h.sdkReady();ready();await flush();assert.equal(h.maps.length,1);assert.equal(h.win[callback],undefined);assert.equal(script.onload,null);assert.equal(script.onerror,null);
  ready();await flush();assert.equal(h.maps.length,1,'duplicate readiness callbacks do not recreate the map');h.close();
  h=setup({sdkPending:true,fakeTimers:true});h.feature.open();await flush();
  script=h.win.document.querySelector('script');callback=new URL(script.src).searchParams.get('callback');const lateReady=h.win[callback],lateLoad=script.onload;
  h.feature.close();await flush();assert.equal(h.win[callback],undefined);assert.equal(script.isConnected,false);assert.equal(h.timers.size,0);
  h.feature.open();await flush();const newScript=h.win.document.querySelector('script'),newCallback=new URL(newScript.src).searchParams.get('callback');
  assert.notEqual(newCallback,callback,'each pending load has its own callback');h.sdkReady();lateReady();lateLoad();await flush();
  assert.equal(h.maps.length,0,'callbacks retained from the cancelled load cannot initialize a reopened map');
  h.win[newCallback]();await flush();assert.equal(h.maps.length,1);assert.equal(h.win[newCallback],undefined);assert.equal(h.timers.size,0);h.close();
  h=setup({sdkPending:true,fakeTimers:true});h.feature.open();await flush();
  script=h.win.document.querySelector('script');callback=new URL(script.src).searchParams.get('callback');const timeoutReady=h.win[callback];script.onload();h.advance(16000);await flush();
  assert.match(h.el('status').textContent,/高德地图加载超时/);assert.equal(h.win[callback],undefined);assert.equal(script.isConnected,false);assert.equal(h.timers.size,0);assert.equal(h.el('reload').disabled,false);
  h.sdkReady();timeoutReady();await flush();assert.equal(h.maps.length,0,'a callback arriving after timeout cannot revive the map');h.close();
  h=setup({sdkPending:true,fakeTimers:true});h.feature.open();await flush();script=h.win.document.querySelector('script');callback=new URL(script.src).searchParams.get('callback');h.sdkReady();script.onload();await flush();
  assert.equal(h.maps.length,1,'onload can complete immediately when the SDK is already ready');assert.equal(h.win[callback],undefined);h.close();
  console.log('AMap lens tests passed: provider, heading-up, location conversion, late callbacks, IMU cleanup and missing-key simulation.');
})().catch(error=>{console.error(error);process.exitCode=1;});
