const assert = require('node:assert/strict');
const { HardwareSimulator, modes } = require('../lg_assistant/web/static/hardware-engine.js');
(async () => {
  assert.deepEqual(modes, ['拍照解题', '会议纪要', '实时翻译', '地图']);
  const engine = new HardwareSimulator({wait: async () => {}});
  assert.equal(await engine.send('press'), true);
  assert.equal(engine.state.photos, 1);
  assert.equal(engine.state.events[0].stage, '回执');
  engine.connect(false);
  assert.equal(await engine.send('press'), false);
  assert.equal(engine.state.photos, 1, 'disconnected capture must not execute');
  engine.connect(true);
  assert.equal(engine.state.photos, 1, 'reconnect must never replay a shutter command');
  engine.setFault('timeout');
  assert.equal(await engine.send('press'), false);
  assert.equal(engine.state.photos, 1);
  assert.equal(engine.state.fault, 'none', 'fault injection applies only once');
  engine.setFault('reject');
  assert.equal(await engine.send('next'), false);
  assert.equal(engine.state.mode, 0, 'device failure must not switch scenes');
  await engine.send('next'); assert.equal(engine.state.mode, 1);
  await engine.send('next'); assert.equal(engine.state.mode, 2);
  await engine.send('next'); assert.equal(engine.state.mode, 3);
  await engine.send('next'); assert.equal(engine.state.mode, 0);
  await engine.send('previous'); assert.equal(engine.state.mode, 3);
  await engine.send('press');assert.match(engine.state.feedback,/地图/);assert.equal(engine.state.photos,1,'map commands do not trigger the camera');
  await engine.send('previous');await engine.send('press');assert.match(engine.state.feedback,/实时翻译/);assert.equal(engine.state.photos,1,'translation commands do not trigger the camera');
  let resume;
  const delayed = new HardwareSimulator({wait: () => new Promise(r => {resume = r;})});
  const pending = delayed.send('press');
  assert.equal(await delayed.send('press'), false, 'duplicate inputs are ignored while busy');
  delayed.connect(false); resume();
  assert.equal(await pending, false);
  assert.equal(delayed.state.photos, 0, 'disconnect cancels in-flight work');
  const pendingReset = delayed.send('press'); delayed.reset(); resume();
  assert.equal(await pendingReset, false);
  assert.equal(delayed.state.photos, 0, 'reset invalidates outstanding commands');
  console.log('Hardware control: success, disconnect, timeout, rejection, scene cycle, duplicate input and reset passed.');
})().catch(e => {console.error(e); process.exitCode = 1;});
