const assert=require('node:assert/strict');
const {HardwareNavigation,HardwareSimulator,HardwareMediaSession}=require('../lg_assistant/web/static/hardware-engine.js');
const {bindInput,classifyGesture}=require('../lg_assistant/web/static/smart-ring.js');
(async()=>{
  const nav=new HardwareNavigation();
  const apply=(action,data)=>{const plan=nav.plan(action,data);nav.commit(plan);return plan.effect;};
  for(const mode of [0,1]) {
    assert.equal(nav.options(mode).length,mode===0?6:4,'capture, settings and explicit old-photo rerun are operations; return remains a gesture');
    assert.ok(nav.options(mode).every(label=>!label.includes('返回')));
    apply(`scene${mode}`);apply('read',{hasResult:true});
    apply('back');assert.equal(nav.state.screen,'actions','long press returns to operations first');
    apply('back');assert.equal(nav.state.screen,'home');assert.equal(nav.state.mode,mode);
    apply('back');assert.equal(nav.state.screen,'home','return at the root remains on scene selection');
  }
  for(const [mode,label] of [[2,'打开实时翻译'],[3,'打开地图']]) {
    apply(`scene${mode}`);
    assert.deepEqual(nav.options(mode),[label],'new scene menus expose their own feature action');
    assert.equal(apply('press',{hasFile:true,hasResult:true}),'featureOpen','feature scenes do not reuse retained photo/audio processing');
    assert.equal(nav.state.screen,'feature');
    assert.equal(apply('press'),'featureSelect','ring confirmation activates a feature control');
    assert.equal(apply('next'),'controlNext');assert.equal(apply('previous'),'controlPrevious');
    assert.equal(apply('read',{hasResult:true}),'none','the old read shortcut cannot open meeting results in a feature scene');
    apply('back');assert.equal(nav.state.screen,'actions');
    apply('back');assert.equal(nav.state.screen,'home');assert.equal(nav.state.mode,mode);
  }
  assert.equal(nav.options(0)[4],'解题设置','adding rerun must not move the existing settings choice');
  assert.equal(nav.options(0)[5],'重新解答当前图片','reusing a retained photo is an explicitly named operation');
  for(const hasPendingPhoto of [false,true]) {
    nav.state={screen:'actions',mode:1,focus:0};
    assert.equal(apply('press',{hasFile:true,hasResult:true,hasPendingPhoto}),'record','pending-photo state does not replace the existing meeting recording action');
    apply('back');
  }
  assert.equal(apply('rerun',{hasFile:true,hasResult:true,hasPendingPhoto:false}),'none','the photo-only rerun action cannot generate meeting notes');
  apply('focus2');assert.equal(apply('press',{hasFile:true,hasResult:true}),'run','meeting generation remains its existing explicit operation');
  nav.reset();
  apply('next');assert.equal(nav.state.mode,1);assert.equal(nav.state.screen,'home');
  apply('press');assert.equal(nav.state.screen,'actions');assert.equal(nav.state.focus,0);
  assert.equal(apply('press'),'record');assert.equal(nav.state.screen,'recording');
  assert.equal(apply('press'),'recordToggle');
  assert.equal(apply('next'),'controlNext','record panel cycles real controls');
  apply('back');assert.equal(nav.state.screen,'actions');
  apply('focus1');assert.equal(apply('press'),'import');
  apply('focus2');assert.equal(apply('press'),'missing');assert.equal(nav.state.focus,0);
  apply('focus2');assert.equal(apply('press',{hasFile:true}),'run');
  apply('read',{hasResult:true});
  for(const action of ['down','next'])assert.equal(apply(action),'scrollDown');
  for(const action of ['up','previous'])assert.equal(apply(action),'scrollUp');
  assert.equal(nav.state.mode,1,'reading never switches scenes');
  apply('double');assert.equal(nav.state.screen,'actions');
  apply('home');assert.equal(nav.state.screen,'home');assert.equal(nav.state.focus,1);
  apply('scene0');assert.equal(nav.state.mode,0);
  assert.equal(apply('press'),'camera','first photo opens camera if there is no imported image');
  assert.equal(nav.state.screen,'camera');assert.equal(apply('press'),'capture');
  apply('back');assert.equal(nav.state.screen,'actions');
  assert.equal(apply('press',{hasFile:true,hasResult:false}),'run','legacy callers without pending-photo state retain their default fresh-photo behavior');
  assert.equal(apply('press',{hasFile:true,hasResult:false,hasPendingPhoto:true}),'run','an explicitly pending imported photo runs without opening another camera');
  assert.equal(apply('press',{hasFile:true,hasResult:false,hasPendingPhoto:false}),'camera','an old submitted photo reopens the camera even if the previous API attempt failed without a result');
  apply('back');
  assert.equal(apply('press',{hasFile:true,hasResult:true}),'camera','the main photo action opens the camera again after completing an old photo');
  apply('back');
  for(const hasResult of [false,true])for(const hasPendingPhoto of [false,true]) {
    nav.state={screen:'actions',mode:0,focus:0};
    assert.equal(apply('rerun',{hasFile:true,hasResult,hasPendingPhoto}),'run','explicit rerun uses the retained file independent of prior answer or pending-photo state');
    assert.equal(nav.state.screen,'actions','explicit rerun does not open camera or change operation focus');
  }
  nav.state={screen:'actions',mode:0,focus:0};
  assert.equal(apply('rerun',{hasFile:false,hasResult:true}),'missing','a past answer alone is insufficient to rerun a missing photo');
  assert.notEqual(nav.state.screen,'camera','missing-photo rerun only gives a reminder');
  apply('focus5');
  for(const hasResult of [false,true])for(const hasPendingPhoto of [false,true])assert.equal(apply('press',{hasFile:true,hasResult,hasPendingPhoto}),'run','the last photo-menu choice explicitly reruns the current image regardless of pending-photo state');
  assert.notEqual(nav.state.screen,'camera');
  assert.equal(apply('press',{hasFile:false}),'missing','the rerun menu choice never silently takes another photo');
  apply('focus0');
  apply('next');apply('next');assert.equal(apply('press'),'missing');
  assert.equal(apply('press',{hasResult:true}),'read');
  apply('back');
  for(const hasFile of [false,true])for(const hasResult of [false,true]) {
    nav.state={screen:'actions',mode:0,focus:3};
    assert.equal(apply('press',{hasFile,hasResult}),'camera','the retake choice always opens the camera');
    apply('back');
  }
  apply('focus4');assert.equal(apply('press'),'settings');
  assert.equal(nav.state.screen,'settings');assert.equal(apply('press'),'settingsSelect');
  apply('back');assert.equal(nav.state.screen,'actions','settings returns to its scene operations');
  nav.state={screen:'practice',mode:0,focus:0};assert.equal(apply('next'),'controlNext');assert.equal(apply('press'),'practiceSelect');apply('back');assert.equal(nav.state.screen,'result','practice returns to full learning results before the operation menu');apply('back');assert.equal(nav.state.screen,'actions');
  nav.state={screen:'settings',mode:0,focus:0,returnScreen:'result'};apply('back');assert.equal(nav.state.screen,'result','manual classification returns to the original OCR result');assert.equal(nav.state.returnScreen,undefined);
  const pendingStreams=[];let released=0;
  const media=new HardwareMediaSession(()=>new Promise(resolve=>pendingStreams.push(resolve)));
  const fakeStream=()=>({getTracks:()=>[{stop(){released++;}}]});
  const late=media.start({video:true});assert.equal(media.active,true);media.stop();
  pendingStreams.shift()(fakeStream());assert.equal(await late,null);assert.equal(released,1,'a permission result arriving after back is immediately released');
  const older=media.start({video:true}),newer=media.start({audio:true});
  pendingStreams.shift()(fakeStream());pendingStreams.shift()(fakeStream());
  assert.equal(await older,null,'an old capture request cannot replace a new lens session');
  assert.ok(await newer);assert.equal(media.active,true);media.stop();assert.equal(released,3);assert.equal(media.active,false);
  const failed=new HardwareMediaSession(async()=>{throw new Error('denied');});
  await assert.rejects(failed.start({audio:true}),/denied/);assert.equal(failed.active,false,'permission failure never retains the recording lock');
  const engine=new HardwareSimulator({wait:async()=>{}});
  engine.setFault('reject');let executed=false;
  assert.equal(await engine.send('navigate',{execute:()=>{executed=true;}}),false);
  assert.equal(executed,false,'rejected navigation cannot advance screen');
  await engine.send('navigate',{execute:()=>{executed=true;return 'selected';}});assert.equal(executed,true);
  assert.equal(classifyGesture({dy:-60,vertical:true}),'up');
  assert.equal(classifyGesture({dy:60,vertical:true}),'down');
  const handlers={},actions=[];
  const button={disabled:false,classList:{add(){},remove(){}},addEventListener:(type,fn)=>handlers[type]=fn,setPointerCapture(){}};
  const binding=bindInput(button,{action:a=>actions.push(a),doubleTap:true});
  handlers.click({detail:1});handlers.click({detail:2});
  await new Promise(r=>setTimeout(r,320));assert.deepEqual(actions,['double'],'double tap must never first submit');
  handlers.click({detail:1});await new Promise(r=>setTimeout(r,320));assert.deepEqual(actions,['double','press']);
  handlers.click({detail:1});binding.cancel();await new Promise(r=>setTimeout(r,320));assert.equal(actions.length,2,'route/mode changes cancel pending tap');
  handlers.click({detail:0});assert.equal(actions.at(-1),'press');
  nav.state={screen:'actions',mode:0,focus:0};
  assert.deepEqual(nav.drag(-44),{focus:5},'the first photo choice wraps upward to its new explicit rerun choice');
  for(const total of [-264,264,-792,792])assert.deepEqual(nav.drag(total),{focus:0},'complete six-choice photo loops return to the initial focus');
  apply('focus5');assert.deepEqual(nav.drag(44),{focus:0},'the rerun choice wraps downward to the main camera choice');
  for(let i=0;i<12;i++) {
    const preview=nav.drag(-44);apply(`focus${preview.focus}`);
    assert.equal(nav.state.focus,[4,3,2,1,0,5][i%6],'released swipes traverse every photo choice through repeated six-choice loops');
    assert.equal(nav.state.screen,'actions','cycling photo choices never opens the camera or triggers rerun');
  }
  apply('focus6');assert.equal(nav.state.focus,5,'an out-of-range seventh photo choice cannot be selected');
  nav.reset();assert.deepEqual(nav.drag(-44),{focus:3},'first scene wraps upward to last');
  assert.deepEqual(nav.drag(-43),{focus:0},'small movements do not change selection');
  assert.deepEqual(nav.drag(-220),{focus:3},'one continuous drag can pass the scene boundary repeatedly');
  assert.deepEqual(nav.drag(220),{focus:1});
  assert.deepEqual(nav.drag(176),{focus:0},'a full loop returns to the starting option');
  assert.equal(nav.state.focus,0,'drag preview does not commit before release');
  apply('focus3');assert.equal(nav.state.mode,3);assert.deepEqual(nav.drag(44),{focus:0},'last scene wraps downward to first');
  apply('focus1');assert.equal(nav.state.mode,1);
  apply('press');assert.deepEqual(nav.drag(-44),{focus:3},'first action wraps upward to last');
  assert.deepEqual(nav.drag(-528),{focus:0},'three complete upward action loops return to the start');
  assert.deepEqual(nav.drag(528),{focus:0},'three complete downward action loops return to the start');
  apply('focus4');assert.equal(nav.state.focus,0,'out of range choice cannot be selected');
  apply('focus3');assert.deepEqual(nav.drag(44),{focus:0},'last action wraps downward to first');
  for(let i=0;i<12;i++) {
    const preview=nav.drag(-44);apply(`focus${preview.focus}`);
    assert.equal(nav.state.focus,[2,1,0,3][i%4],'repeated released swipes continue looping');
    assert.equal(nav.state.screen,'actions','selection gestures never execute an operation');
  }
  apply('read',{hasResult:true});assert.deepEqual(nav.drag(20,100,500),{scrollTop:140});assert.deepEqual(nav.drag(-300,100,500),{scrollTop:0});assert.deepEqual(nav.drag(300,100,500),{scrollTop:500});
  const flowEvents=[],flowActions=[],flowRotations=[],flowHandlers={};let inspectOnly=false;
  const flowButton={disabled:false,classList:{add(){},remove(){}},addEventListener:(type,fn)=>flowHandlers[type]=fn,setPointerCapture(){}};
  const flowBinding=bindInput(flowButton,{flow:true,doubleTap:true,action:a=>flowActions.push(a),onFlow:e=>flowEvents.push(e),rotate:(x,y)=>flowRotations.push([x,y]),inspect:()=>inspectOnly});
  const fire=(type,extra={})=>flowHandlers[type]({pointerId:1,isPrimary:true,button:0,clientX:0,clientY:0,timeStamp:0,detail:1,preventDefault(){},...extra});
  fire('pointerdown');fire('pointermove',{clientY:20});fire('pointermove',{clientY:88});
  assert.deepEqual(flowEvents.map(e=>e.phase),['start','move','move']);assert.equal(flowEvents.at(-1).total,88);assert.deepEqual(flowRotations,[],'navigation drag must not rotate the ring');
  fire('pointerup',{clientY:88});fire('click');await new Promise(r=>setTimeout(r,320));assert.deepEqual(flowActions,[],'drag release cannot also click or navigate twice');assert.equal(flowEvents.at(-1).phase,'end');
  fire('pointerdown');fire('pointermove',{clientY:-70});flowBinding.cancel();fire('click');assert.equal(flowEvents.at(-1).phase,'cancel');
  assert.deepEqual(flowRotations,[],'upward and canceled navigation also keep the model steady');
  const flowCount=flowEvents.length;inspectOnly=true;fire('pointerdown');fire('pointermove',{clientY:60});fire('pointerup',{clientY:60});assert.equal(flowEvents.length,flowCount,'inspection rotates without changing selection');assert.deepEqual(flowRotations,[[0,60]],'inspection explicitly enables model rotation');
  inspectOnly=false;fire('pointerdown');fire('pointerup',{timeStamp:800});fire('click');
  assert.deepEqual(flowActions,['back'],'long press returns one page without a second click, even with double-tap support');
  const tapHandlers={},tapActions=[];
  const tapButton={...flowButton,addEventListener:(type,fn)=>tapHandlers[type]=fn};
  bindInput(tapButton,{action:a=>{tapActions.push(a);apply(a);}});
  const tapFire=(type,timeStamp)=>tapHandlers[type]({pointerId:2,isPrimary:true,button:0,clientX:0,clientY:0,timeStamp,detail:1,preventDefault(){}});
  tapFire('pointerdown',0);tapFire('pointerup',800);tapFire('click',800);
  assert.deepEqual(tapActions,['back']);assert.equal(nav.state.screen,'actions','holding on a result returns to operations, never the root');
  tapFire('pointerdown',1000);tapFire('pointerup',1800);tapFire('click',1800);
  assert.deepEqual(tapActions,['back','back']);assert.equal(nav.state.screen,'home');
  tapFire('pointerdown',2000);tapFire('pointerup',2050);tapFire('click',2050);
  assert.deepEqual(tapActions,['back','back','press'],'light tap confirms immediately');assert.equal(nav.state.screen,'actions');
  console.log('Continuous drag: stable ring during selection, inspection rotation, cyclic menus, scroll boundaries, cancellation, inspect-only and no extra click passed.');
  console.log('Context navigation: scene/action focus, imports, genuine run, reading, back/home, faults, vertical gestures and exclusive double tap passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
